### ISSUE TITLE
tsod tsod.ConstantGradientDetector() so slow!!

### ISSUE THREAD

**Issue by KevinLu233** [DHI/tsod#36]
I used tsod.ConstantGradientDetector() with 32 data points every time ,but it cost 20ms at 3.0GHz cpu!
TSOD used many numpy dataset,can you used numba ，then make it run fast! 
thank you!

**Comment by ecomodeller** [comment]
Thanks for your comment.

We know that performance is important, but we have limited resources for development.

If you have a suggestion on how to improve the perfomance you are very welcome to submit a Pull Request.

**Comment by KevinLu233** [comment]
Ok.  I Will Try it ! 
Thank You
