### ISSUE TITLE
How can I save and load trained model?

### ISSUE THREAD

**Issue by Mekako** [DHI/tsod#48]
I have trained a RollingStandardDeviationDetector and saved it.
```
rsd = RollingStandardDeviationDetector ()
rsd.fit(data)
rsd.save('./test.model')
```
How Can I load it from the 'test.model'?
There are only 4 functions for it : `fit`, `detect`, `validate`and `save`.
Looking forward to reply!

**Comment by ecomodeller** [comment]
> I have trained a RollingStandardDeviationDetector and saved it.
> 
> ```
> rsd = RollingStandardDeviationDetector ()
> rsd.fit(data)
> rsd.save('./test.model')
> ```
> 
> How Can I load it from the 'test.model'? There are only 4 functions for it : `fit`, `detect`, `validate`and `save`. Looking forward to reply!

It should be as simple as `tsod.load` https://dhi.github.io/tsod/getting_started.html#saving-and-loading, let us know if that is not the case.

**Comment by Mekako** [comment]
> > I have trained a RollingStandardDeviationDetector and saved it.
> > ```
> > rsd = RollingStandardDeviationDetector ()
> > rsd.fit(data)
> > rsd.save('./test.model')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How Can I load it from the 'test.model'? There are only 4 functions for it : `fit`, `detect`, `validate`and `save`. Looking forward to reply!
> 
> It should be as simple as `tsod.load` https://dhi.github.io/tsod/getting_started.html#saving-and-loading, let us know if that is not the case.

I use `joblib.load()` and it works well.
Thanks for replying!
